services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - /root/docker/minecraft/data:/data
    environment:
      - EULA=TRUE
      - TYPE=FABRIC
      - MODRINTH_PROJECTS=lithium
      - MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES=true
      - MODRINTH_ALLOWED_VERSION_TYPE=release