services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
    volumes:
      - /root/docker/qb/config:/config
      - /root/docker/qb/downloads:/downloads
    networks: "host"
    restart: unless-stopped